# Generated by Django 4.2.24 on 2025-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Описание пользователя'),
        ),
    ]
