# Generated by Django 4.2.24 on 2025-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Новости'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Оповещения'),
        ),
    ]
