# Generated by Django 4.2.24 on 2025-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_newsletter_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Описание пользователя'),
        ),
    ]
